### ISSUE TITLE
Conflicting implementations of trait `Debug` for type `RunningStateBits`

### ISSUE THREAD

**Issue by dominikwilkowski** [bjeanes/modbus-mqtt#5]
Hi there,

I'm getting an error when trying to compile:

```sh
λ cargo run
   Compiling sungrow-winets v0.1.0
error[E0119]: conflicting implementations of trait `Debug` for type `RunningStateBits`
   --> /Users/dominik/.cargo/registry/src/github.com-1ecc6299db9ec823/sungrow-winets-0.1.0/src/lib.rs:255:1
    |
255 | #[bitmask_enum::bitmask(u16)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `RunningStateBits`
256 | #[derive(Debug)]
    |          ----- first implementation here
    |
    = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0119`.
error: could not compile `sungrow-winets` due to previous error
```

Some system infos:

```sh
λ rustc -V
rustc 1.69.0 (84c898d65 2023-04-16)
λ arch
arm64
λ sw_vers
ProductName:		macOS
ProductVersion:		13.4
BuildVersion:		22F66
```

My `Cargo.toml`

```toml
[package]
name = "solar"
version = "0.1.0"
edition = "2021"

[dependencies]
sungrow-winets = "0.1.0"
```

And my `main.rs`

```rust
fn main() {
	println!("hello world");
}
```

**Comment by bjeanes** [comment]
Hey thanks for opening an issue!

I think I saw this last week myself after upgrading `bitmask_enum`. It seems to provide `Debug` itself. I think removing the derive may suffice, but I am checking locally now.

**Comment by bjeanes** [comment]
Ah I think I just need to release a new version of that crate. Can you try pulling in the crate as a git dependency and let me know if that works? If so, I'll release a bumped version.

**Comment by dominikwilkowski** [comment]
That seems to work.

This is my `Cargo.toml` now
```toml
[package]
name = "solar"
version = "0.1.0"
edition = "2021"

[dependencies]
sungrow-winets = { git = "https://github.com/bjeanes/modbus-mqtt.git" }
tokio = { version = "1.28.1", features = ["full"] }
tracing-subscriber = "0.3.17"
```

And `main.rs`
```rust
use std::time::Duration;

use sungrow_winets::*;

#[tokio::main]
async fn main() -> Result<(), Error> {
	tracing_subscriber::fmt::init();

	let host = std::env::args().nth(1).expect("must pass host/IP of WiNet-S as first argument");

	let client = Client::new(host).await?;

	let mut tick = tokio::time::interval(Duration::from_millis(200));
	loop {
		tick.tick().await;
		let data = client.running_state().await;
		println!("{:?}", &data);
	}
}
```

Note that I had to install `tracing-subscriber` as well which was included in the example without a note?

```sh
λ cargo run -- 10.0.0.101
   Compiling solar v0.1.0 (/Users/dominik/Sites/solar)
    Finished dev [unoptimized + debuginfo] target(s) in 0.80s
     Running `target/debug/solar 10.0.0.101`
Err(SungrowError { code: 301, message: Some("I18N_COMMON_READ_FAILED") })
Err(SungrowError { code: 301, message: Some("I18N_COMMON_READ_FAILED") })
^C
```

I'm getting a `I18N_COMMON_READ_FAILED` error now so no compile error anymore which means this issue is fixed with the code in the latest `main` branch. I take it that `I18N_COMMON_READ_FAILED` is common and a bit weird. Will dig into that later
