### ISSUE TITLE
Problems on MQTT disconnect

### ISSUE THREAD

**Issue by git-developer** [bjeanes/modbus-mqtt#6]
#### Scenario
I'm using modbus-mqtt in a Docker container to periodically publish values of a power meter.

#### Problem
I recently restarted the MQTT broker. modbus-mqtt stopped working from this moment, showing the following log entry:
```
2023-06-03T06:20:15.796005Z ERROR modbus_mqtt::server: MQTT connection error cause=I/O: Connection reset by peer (os error 104)
```

After restarting the container and reconfiguring modbus-mqtt, everything continued to work.

I'm experiencing 2 issues:
1. modbus-mqtt does not reconnect to the broker.
2. The configuration is lost after reconnection.

#### Suggestion 1: Reconnect to the MQTT broker
I tried to solve the first issue by implmenting a health check:
```yaml
services:
  modbus-mqtt:
    image: "bjeanes/modbus-mqtt:edge-alpine"
    restart: unless-stopped
    command: "mqtt://broker"
    healthcheck:
      test: netstat -t | grep ':1883\s\+ESTABLISHED' -q || kill 1
      timeout: 5s
      start_period: 5s
```
This works but feels a bit cumbersome to me. A disadvantage is that the configuration is lost after restart. I'd prefer to configure modbus-mqtt to reconnect to the broker, keeping the configuration.

#### Suggestion 2: Add configuration on start
The second issue could be solved by allowing a configuration file as command line argument. I'm currently using a second docker container that publishes the configuration after modbus-mqtt has booted:
```yaml
services:
  modbus-mqtt:
  [...]

  modbus-mqtt-init:
    environment:
      MQTT_BROKER: broker
      MQTT_TOPIC: meter
    volumes:
      - "./modbus-mqtt.json:/etc/modbus-mqtt.json:ro"
    image: modbus-mqtt-init
    container_name: modbus-mqtt-init
    build:
      dockerfile_inline: |
        FROM alpine
        RUN apk add --no-cache mosquitto-clients
        CMD mosquitto_pub -h "$${MQTT_BROKER}" -t "modbus-mqtt/$${MQTT_TOPIC}/connect" -s </etc/modbus-mqtt.json
    depends_on:
      - modbus-mqtt
```
This works for a normal service start, but unfortunately doesn't work on MQTT disconnect.

---
❤ Thanks for this great project which perfectly suits my needs! ❤
